[package]
name = "principal-discord-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15", features = ["macros", "rt-multi-thread"]}
dotenv = "0.15"
resvg = "0.19"
usvg = "0.19"
tiny-skia = "0.6"
