[package]
name = "principal-discord-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15"
serenity = { version = "0.10", default-features = false, features = [
  "rustls_backend",
  "builder",
  "cache",
  "client",
  "gateway",
  "model",
  "utils",
  "framework",
  "standard_framework",
  # "unstable_discord_api",
] }
tracing-subscriber = "0.3"
tracing-unwrap = "0.9"
tracing = "0.1"
